FROM node:16-alpine

ENV export http_proxy="http://internet.cetin:8080"
ENV export https_proxy="http://internet.cetin:8080"

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]